CREATE TABLE IF NOT EXISTS addbook(
DeleteID INT UNSIGNED NOT NULL AUTO_INCREMENT ,
AuthorID VARCHAR (10) NOT NULL ,
item_name VARCHAR(20) NOT NULL ,
item_desc VARCHAR(200) NOT NULL ,
ISBN INT(13) NOT NULL ,
item_img VARCHAR(20) NOT NULL ,
item_price DECIMAL(4,2) NOT NULL ,
PRIMARY KEY (DeleteID));